
import { StaticImageData } from "next/image";
import { 
    cap1, cap2, cap3, cap4, cap5, 
    sneakers1, sneakers2, sneakers3, sneakers4, sneakers5, 
    tshirt1, tshirt2, tshirt3, tshirt4, tshirt5, 
    trousers1, trousers2, trousers3, trousers4, trousers5,
    timer1, timer2, timer4, timer3, timer5,
    fashion_achievement1, fashion_achievement2, fashion_achievement3,
    friendship_achievement1, friendship_achievement2, friendship_achievement3,
    timekeeper_achievement1, timekeeper_achievement2, timekeeper_achievement3,
    coin,
    box,
    ticket,
    airpods, 
} from "./img/images";

export type Сard = {
  level: number,
  speed: number,
  price: number,
  title: string,
  headline: string,
  text: string,
  image: string,
}

interface Cards {
  cap: Сard[],
  tshirt: Сard[],
  trousers: Сard[],
  sneakers: Сard[],
  time: Сard[]
}

export const cards: Cards = {
  cap: [
        {
          level: 1,
          speed: 0.24,
          price: 130,
          title: 'Basic Green',
          headline: 'Green cap, simple edition',
          text: 'This entry-level cap offers basic protection from the sun and a minimalist design. Perfect for everyday wear, it provides a comfortable fit and breathable material. Ideal for casual outings and lounging, but not intended for intense activities or long-term use.',
          image: cap1,
        },
        {
          level: 2,
          speed: 0.28,
          price: 170,
          title: 'Royal Sapphire',
          headline: 'Sapphire cap, moderate edition',
          text: 'This mid-range cap features a rich sapphire color and improved material quality. It offers a comfortable fit and enhanced breathability, making it suitable for regular outdoor activities and casual wear. A reliable choice for both active and laid-back days.',
          image: cap2,
        },
        {
          level: 3,
          speed: 0.33,
          price: 250,
          title: 'Radiant Ruby',
          headline: 'Ruby cap, vibrant edition',
          text: 'This high-quality cap showcases a striking ruby hue and premium materials. Designed for those who appreciate style and comfort, it offers a tailored fit and superior breathability. Perfect for making a statement, whether at the gym, on the trail, or out on the town.',
          image: cap3,
        },
        {
          level: 4,
          speed: 0.45,
          price: 400,
          title: 'Honeyed Amber',
          headline: 'Amber cap, nature-inspired edition',
          text: 'Inspired by the warmth of honey and the beauty of nature, this cap combines style with functionality. It provides exceptional comfort and a unique design, perfect for outdoor adventures or casual urban wear. A great choice for those who value both aesthetics and performance.',
          image: cap4,
        },
        {
          level: 5,
          speed: 0.74,
          price: 1000,
          title: 'Epic Galaxy',
          headline: 'Galaxy cap, elite edition',
          text: 'This elite cap features a stunning galaxy design and the highest quality materials. Engineered for those who demand the best, it delivers unparalleled comfort, durability, and style. Ideal for achieving your personal best, whether in athletic pursuits or making a bold fashion statement.',
          image: cap5,
        },
  ],
  tshirt: [
      {
          level: 1,
          speed: 0.24,
          price: 180,
          title: 'Basic Green',
          headline: 'Green T-shirt, simple edition',
          text: 'This entry-level T-shirt offers basic comfort and a minimalist design. Perfect for everyday wear, it provides a relaxed fit and breathable fabric. Ideal for casual outings and lounging at home, but not intended for intense activities or long-term use.',
          image: tshirt1,
        },
        {
          level: 2,
          speed: 0.36,
          price: 240,
          title: 'Royal Sapphire',
          headline: 'Sapphire T-shirt, moderate edition',
          text: 'This mid-range T-shirt features a rich sapphire color and improved fabric quality. It offers a comfortable fit and enhanced breathability, making it suitable for regular workouts and casual wear. A reliable choice for both active and laid-back days.',
          image: tshirt2,
        },
        {
          level: 3,
          speed: 0.5,
          price: 350,
          title: 'Radiant Ruby',
          headline: 'Ruby T-shirt, vibrant edition',
          text: 'This high-quality T-shirt showcases a striking ruby hue and premium materials. Designed for those who appreciate style and comfort, it offers a tailored fit and superior softness. Perfect for making a statement, whether at the gym or out on the town.',
          image: tshirt3,
        },
        {
          level: 4,
          speed: 0.71,
          price: 600,
          title: 'Honeyed Amber',
          headline: 'Amber T-shirt, nature-inspired edition',
          text: 'Inspired by the warmth of honey and the beauty of nature, this T-shirt combines style with functionality. It provides exceptional comfort and a unique design, perfect for outdoor adventures or casual urban wear. A great choice for those who value both aesthetics and performance.',
          image: tshirt4,
        },
        {
          level: 5,
          speed: 0.96,
          price: 1200,
          title: 'Epic Galaxy',
          headline: 'Galaxy T-shirt, elite edition',
          text: 'This elite T-shirt features a stunning galaxy design and the highest quality fabric. Engineered for those who demand the best, it delivers unparalleled comfort, durability, and style. Ideal for achieving your personal best, whether in athletic pursuits or making a bold fashion statement.',
          image: tshirt5,
        },
  ],
  trousers: [
      {
          level: 1,
          speed: 0.24,
          price: 130,
          title: 'Basic Green',
          headline: 'Green trousers, casual edition',
          text: 'These entry-level trousers offer essential comfort and simplicity. Perfect for everyday wear, they feature a relaxed fit and breathable fabric. Ideal for casual outings and relaxed home settings, but not designed for intense activities or formal occasions.',
          image: trousers1,
        },
        {
          level: 2,
          speed: 0.34,
          price: 180,
          title: 'Royal Sapphire',
          headline: 'Sapphire trousers, comfort edition',
          text: 'These mid-range trousers come in a regal sapphire hue, offering improved quality and comfort. With a modern fit and enhanced durability, they are suitable for regular use, from casual Fridays at the office to weekend adventures. A dependable choice for everyday versatility.',
          image: trousers2,
        },
        {
          level: 3,
          speed: 0.48,
          price: 260,
          title: 'Radiant Ruby',
          headline: 'Ruby trousers, stylish edition',
          text: 'These high-quality trousers shine in a radiant ruby color, blending style with functionality. Designed for those who value both aesthetics and performance, they provide a tailored fit and superior fabric. Perfect for making a bold fashion statement, whether at a social event or a business meeting.',
          image: trousers3,
        },
        {
          level: 4,
          speed: 0.64,
          price: 370,
          title: 'Honeyed Amber',
          headline: 'Amber trousers, nature-inspired edition',
          text: 'Inspired by the warmth of honey and the charm of nature, these trousers offer a unique blend of style and comfort. Featuring a relaxed yet refined fit, they are ideal for outdoor excursions or urban explorations. Perfect for those who appreciate natural beauty and high-quality craftsmanship.',
          image: trousers4,
        },
        {
          level: 5,
          speed: 0.82,
          price: 600,
          title: 'Epic Galaxy',
          headline: 'Galaxy trousers, elite edition',
          text: 'These elite trousers boast a mesmerizing galaxy design, merging cutting-edge fashion with peak performance. Engineered for those who demand the best, they offer unmatched comfort, durability, and style. Ideal for achieving your personal best, whether in professional settings or making a stellar impression.',
          image: trousers5,
        },
  ],
  sneakers: [
      {
          level: 1,
          speed: 0.27,
          price: 150,
          title: 'Basic Green',
          headline: 'Green sneakers, slow edition',
          text: 'These entry-level running shoes have minimal features and quality, providing basic comfort and support. Ideal for everyday wear, but not intended for intense sports or long-term use.',
          image: sneakers1,
        },
        {
          level: 2,
          speed: 0.35,
          price: 230,
          title: 'Royal Sapphire',
          headline: 'Sapphire sneakers, moderate edition',
          text: 'These mid-range running shoes offer enhanced features and quality, providing improved comfort and support. Suitable for regular workouts and sports activities, they offer a reliable performance for both casual and more dedicated athletes.',
          image: sneakers2,
        },
        {
          level: 3,
          speed: 0.48,
          price: 300,
          title: 'Radiant Ruby',
          headline: 'Ruby sneakers, vibrant edition',
          text: 'These high-quality running shoes feature a striking ruby color and superior craftsmanship. Designed for serious athletes, they offer exceptional support, comfort, and durability. Ideal for intense training sessions and long-distance running, ensuring peak performance.',
          image: sneakers3,
        },
        {
          level: 4,
          speed: 0.67,
          price: 500,
          title: 'Honeyed Amber',
          headline: 'Amber sneakers, nature-inspired edition',
          text: 'Inspired by the beauty of honey and bees, these running shoes blend style with functionality. They provide excellent cushioning and stability, perfect for both outdoor adventures and urban exploration. A great choice for those who appreciate nature and require top-tier athletic performance.',
          image: sneakers4,
        },
        {
          level: 5,
          speed: 0.92,
          price: 940,
          title: 'Epic Galaxy',
          headline: 'Galaxy sneakers, elite edition',
          text: 'These elite running shoes boast a cosmic design and the highest level of performance features. Engineered for those who demand the best, they deliver unmatched comfort, support, and durability. Ideal for achieving your personal best and conquering any challenge, both on and off the track.',
          image: sneakers5,
        },
  ],
  time: [
    {
      level: 1,
      speed: 3,
      price: 160,
      title: 'Basic Green',
      headline: 'Green watch, essential edition',
      text: 'This entry-level watch offers basic timekeeping and a simple design. Perfect for everyday wear, it runs efficiently for up to 3 hours. During this time, it keeps the outfit securely on the mannequin. Ideal for providing essential time management and basic functionality.',
      image: timer1,
    },
    {
      level: 2,
      speed: 4, 
      price: 280,
      title: 'Royal Sapphire',
      headline: 'Sapphire watch, extended edition',
      text: 'This mid-range watch features a stunning sapphire color and an extended battery life. With a sleek design and improved durability, it runs for up to 4 hours. Suitable for regular use, from daily commutes to evening events, offering reliable timekeeping with added functionality.',
      image: timer2,
    },
    {
      level: 3,
      speed: 6,
      price: 400,
      title: 'Radiant Ruby',
      headline: 'Ruby watch, advanced edition',
      text: 'This high-quality watch shines with a radiant ruby hue and superior craftsmanship. Designed for those who appreciate both style and functionality, it runs for up to 6 hours. While active, it maintains the outfit on the mannequin flawlessly. Perfect for busy days and special occasions, providing dependable time management and an impressive display.',
      image: timer3,
    },
    {
      level: 4,
      speed: 12,
      price: 650,
      title: 'Honeyed Amber',
      headline: 'Amber watch, nature-inspired edition',
      text: 'Inspired by the warmth of honey and the beauty of nature, this watch combines style with extended functionality. It runs for up to 12 hours, ensuring the outfit stays secure on the mannequin during this period. Ideal for outdoor adventures or urban explorations, offering long-lasting performance, natural charm, and practical utility.',
      image: timer4,
    },
    {
      level: 5,
      speed: 24,
      price: 1000,
      title: 'Epic Galaxy',
      headline: 'Galaxy watch, elite edition',
      text: 'This elite watch boasts a mesmerizing galaxy design and the highest level of performance. Engineered for those who demand the best, it runs for up to 24 hours, keeping the outfit intact on the mannequin throughout the day. Perfect for achieving your personal best, whether in professional settings or making a stellar impression, this watch ensures you are always on time and well-prepared.',
      image: timer5,
    },
  ]
}

export type TotalDataTypes = 'totalClaimedCoins' | 'totalReferrals' | 'totalClaimedReferralCoins' | 'totalSpendedTime' | 'totalUpgradedLevels' | 'totalClaimedAchievements' | 'totalSwaps'

export type Reward = number | {
  type: 'accessory',
  title: string,
  level: number,
  speed: number,
  image: string,
}

export type Achievement = {
  level: number,
  type: TotalDataTypes
  title: string,
  text: string,
  image: string | StaticImageData,
  goal: number,
  reward: Reward,
  rewardText: string,
  rewardType: string,
  rewardImage: string | StaticImageData,
}

interface Achievements {
  [key: string]:  Achievement[],
}

export const achievements: Achievements = {
  fashion: [
    {
      level: 1,
      type: 'totalUpgradedLevels',
      title: 'First Touch',
      text: 'Welcome to the marketplace! Make your first purchase and begin your adventure in the world of endless possibilities.',
      image: fashion_achievement1,
      goal: 1,
      reward: 10,
      rewardText: '10 coins',
      rewardType: 'balance',
      rewardImage: coin,
    },
    {
      level: 2,
      type: 'totalClaimedCoins',
      title: 'Money Maker',
      text: 'Collect 1,000 coins to fill your treasury with wealth. Keep amassing your fortune and become the ultimate tycoon!',
      image: fashion_achievement2,
      goal: 1000,
      reward: 10,
      rewardText: '10 coins',
      rewardType: 'balance',
      rewardImage: coin,
    },
    {
      level: 3,
      type: 'totalUpgradedLevels',
      title: 'Fashion Monarch',
      text: 'Ascend to the throne of style! Unlock the ultimate fashion level and become the true trendsetter.',
      image: fashion_achievement3,
      goal: 25,
      reward: 1,
      rewardText: '1 ticket',
      rewardType: 'tickets',
      rewardImage: ticket,
    },
  ],
  friendship: [
    {
      level: 1,
      type: 'totalReferrals',
      title: 'Social Starter',
      text: 'Expand your social circle! Invite three friends to join you on this adventure and strengthen your community.',
      image: friendship_achievement1,
      goal: 3,
      reward: {
        type: 'accessory',
        title: 'Airpods',
        level: 1,
        speed: 0.02,
        image: airpods
      },
      rewardText: '1 accessory',
      rewardType: 'accessories',
      rewardImage: box,
    },
    {
      level: 2,
      type: 'totalClaimedReferralCoins',
      title: 'Business family',
      text: 'Reap the rewards of your social network! Earn 100 coins from the profits of your friends.',
      image: friendship_achievement2,
      goal: 100,
      reward: 10,
      rewardText: '10 coins',
      rewardType: 'balance',
      rewardImage: coin,
    },
    {
      level: 3,
      type: 'totalReferrals',
      title: 'Community Builder',
      text: 'Strengthen your connections! Invite five friends to join you on this adventure and create a thriving community together.',
      image: friendship_achievement3,
      goal: 5,
      reward: 1,
      rewardText: '1 ticket',
      rewardType: 'tickets',
      rewardImage: ticket,
    },
  ],
  timekeeper: [
    {
      level: 1,
      type: 'totalSpendedTime',
      title: 'Seasoned Player',
      text: 'Dedication pays off! Spend a 100 hours in the game and showcase your commitment to the adventure.',
      image: timekeeper_achievement1,
      goal: 100,
      reward: 10,
      rewardText: '10 coins',
      rewardType: 'balance',
      rewardImage: coin,
    },
    {
      level: 2,
      title: 'Real deal',
      type: 'totalSwaps',
      text: 'Swap your coins for a real-world discount on the Swap page and unlock exclusive savings.',
      image: timekeeper_achievement2,
      goal: 1,
      reward: 10,
      rewardText: '10 coins',
      rewardType: 'balance',
      rewardImage: coin,
    },
    {
      level: 3,
      type: 'totalClaimedAchievements',
      title: 'Ultimate Completionist',
      text: 'Collect every other achievement in the game to unlock this pinnacle of dedication and mastery.',
      image: timekeeper_achievement3,
      goal: 8,
      reward: 1,
      rewardText: '1 ticket',
      rewardType: 'tickets',
      rewardImage: ticket,
    },
  ],
}