
import { 
    cap1, cap2, cap3, cap4, cap5, 
    sneakers1, sneakers2, sneakers3, sneakers4, sneakers5, 
    tshirt1, tshirt2, tshirt3, tshirt4, tshirt5, 
    trousers1, trousers2, trousers3, trousers4, trousers5,
    timer1, timer2, timer4, timer3, timer5, 
} from "./img/images";

export type Сard = {
  level: number,
  speed: number,
  price: number,
  title: string,
  headline: string,
  text: string,
  image: string,
}

interface Cards {
  cap: Сard[],
  tshirt: Сard[],
  trousers: Сard[],
  sneakers: Сard[],
  time: Сard[]
}

export const cards: Cards = {
  cap: [
        {
          level: 1,
          speed: 0.24,
          price: 140,
          title: 'Basic Green',
          headline: '',
          text: '',
          image: cap1,
        },
        {
          level: 2,
          speed: 0.28,
          price: 150,
          title: 'Royal Sapphire',
          headline: '',
          text: '',
          image: cap2,
        },
        {
          level: 3,
          speed: 0.33,
          price: 160,
          title: 'Radiant Ruby',
          headline: '',
          text: '',
          image: cap3,
        },
        {
          level: 4,
          speed: 0.38,
          price: 140,
          title: 'Honeyed Amber',
          headline: '',
          text: '',
          image: cap4,
        },
        {
          level: 5,
          speed: 0.45,
          price: 140,
          title: 'Epic Galaxy',
          headline: '',
          text: '',
          image: cap5,
        },
  ],
  tshirt: [
      {
          level: 1,
          speed: 0.24,
          price: 140,
          title: 'Basic Green',
          headline: 'Green t-shirt, slow edition',
          text: 'These entry-level running shoes have minimal features and quality, providing basic comfort and support. Ideal for everyday wear, but not intended for intense sports or long-term use.',
          image: tshirt1,
        },
        {
          level: 2,
          speed: 0.28,
          price: 140,
          title: 'Royal Sapphire',
          headline: '',
          text: '',
          image: tshirt2,
        },
        {
          level: 3,
          speed: 0.33,
          price: 140,
          title: 'Radiant Ruby',
          headline: '',
          text: '',
          image: tshirt3,
        },
        {
          level: 4,
          speed: 0.38,
          price: 140,
          title: 'Honeyed Amber',
          headline: '',
          text: '',
          image: tshirt4,
        },
        {
          level: 5,
          speed: 0.45,
          price: 140,
          title: 'Epic Galaxy',
          headline: '',
          text: '',
          image: tshirt5,
        },
  ],
  trousers: [
      {
          level: 1,
          speed: 0.24,
          price: 140,
          title: 'Basic Green',
          headline: 'Green t-shirt, slow edition',
          text: 'These entry-level running shoes have minimal features and quality, providing basic comfort and support. Ideal for everyday wear, but not intended for intense sports or long-term use.',
          image: trousers1,
        },
        {
          level: 2,
          speed: 0.28,
          price: 140,
          title: 'Royal Sapphire',
          headline: '',
          text: '',
          image: trousers2,
        },
        {
          level: 3,
          speed: 0.33,
          price: 140,
          title: 'Radiant Ruby',
          headline: '',
          text: '',
          image: trousers3,
        },
        {
          level: 4,
          speed: 0.38,
          price: 140,
          title: 'Honeyed Amber',
          headline: '',
          text: '',
          image: trousers4,
        },
        {
          level: 5,
          speed: 0.45,
          price: 140,
          title: 'Epic Galaxy',
          headline: '',
          text: '',
          image: trousers5,
        },
  ],
  sneakers: [
      {
          level: 1,
          speed: 0.24,
          price: 140,
          title: 'Basic Green',
          headline: 'Green sneakers, slow edition',
          text: 'These entry-level running shoes have minimal features and quality, providing basic comfort and support. Ideal for everyday wear, but not intended for intense sports or long-term use.',
          image: sneakers1,
        },
        {
          level: 2,
          speed: 0.28,
          price: 140,
          title: 'Royal Sapphire',
          headline: 'Green cap, slow edition',
          text: 'These entry-level running shoes have minimal features and quality, providing basic comfort and support. Ideal for everyday wear, but not intended for intense sports or long-term use.',
          image: sneakers2,
        },
        {
          level: 3,
          speed: 0.33,
          price: 140,
          title: 'Radiant Ruby',
          headline: 'Ruby Blaze Performance Shoes',
          text: 'Step up your game with these radiant ruby-red athletic shoes. Designed for runners, they offer superior comfort, stability, and energy return.',
          image: sneakers3,
        },
        {
          level: 4,
          speed: 0.38,
          price: 140,
          title: 'Honeyed Amber',
          headline: 'Amber Glow Runners',
          text: 'These amber-colored running shoes provide a delightful blend of comfort and durability. Perfect for long runs and outdoor adventures, they’ll have you feeling as cozy as a jar of honey on a sunny morning.',
          image: sneakers4,
        },
        {
          level: 5,
          speed: 0.45,
          price: 140,
          title: 'Epic Galaxy',
          headline: 'Galactic Trailblazers',
          text: 'Reach for the stars with these epic galaxy-themed sneakers. Advanced features, futuristic design, and out-of-this-world performance make them ideal for serious athletes and cosmic explorers.',
          image: sneakers5,
        },
  ],
  time: [
    {
      level: 1,
      speed: 3,
      price: 140,
      title: 'Basic Green',
      headline: 'Green sneakers, slow edition',
      text: 'These entry-level running shoes have minimal features and quality, providing basic comfort and support. Ideal for everyday wear, but not intended for intense sports or long-term use.',
      image: timer1,
    },
    {
      level: 2,
      speed: 4, 
      price: 140,
      title: 'Royal Sapphire',
      headline: '',
      text: '',
      image: timer2,
    },
    {
      level: 3,
      speed: 6,
      price: 140,
      title: 'Radiant Ruby',
      headline: '',
      text: '',
      image: timer3,
    },
    {
      level: 4,
      speed: 12,
      price: 140,
      title: 'Honeyed Amber',
      headline: '',
      text: '',
      image: timer4,
    },
    {
      level: 5,
      speed: 24,
      price: 140,
      title: 'Epic Galaxy',
      headline: '',
      text: '',
      image: timer5,
    },
  ]
}
