import { 
    cap1, cap2, cap3, cap4, cap5, 
    sneakers1, sneakers2, sneakers3, sneakers4, sneakers5, 
    tshirt1, tshirt2, tshirt3, tshirt4, tshirt5, 
    trousers1, trousers2, trousers3, trousers4, trousers5, 
} from "./img/images";

export const cards = {
        cap: [
            {
                level: 1,
                speed: 0.24,
                title: 'Basic Green',
                headline: 'Green cap, slow edition',
                text: 'These entry-level running shoes have minimal features and quality, providing basic comfort and support. Ideal for everyday wear, but not intended for intense sports or long-term use.',
                image: cap1,
                purchased: false,
                locked: false,
              },
              {
                level: 2,
                speed: 0.28,
                title: 'Royal Sapphire',
                headline: '',
                text: '',
                image: cap2,
                purchased: false,
                locked: true,
              },
              {
                level: 3,
                speed: 0.33,
                title: 'Radiant Ruby',
                headline: '',
                text: '',
                image: cap3,
                purchased: false,
                locked: true,
              },
              {
                level: 4,
                speed: 0.38,
                title: 'Honeyed Amber',
                headline: '',
                text: '',
                image: cap4,
                purchased: false,
                locked: true,
              },
              {
                level: 5,
                speed: 0.45,
                title: 'Epic Galaxy',
                headline: '',
                text: '',
                image: cap5,
                purchased: false,
                locked: true,
              },
        ],
        tshirt: [
            {
                level: 1,
                speed: 0.24,
                title: 'Basic Green',
                headline: 'Green t-shirt, slow edition',
                text: 'These entry-level running shoes have minimal features and quality, providing basic comfort and support. Ideal for everyday wear, but not intended for intense sports or long-term use.',
                image: tshirt1,
                purchased: false,
                locked: false,
              },
              {
                level: 2,
                speed: 0.28,
                title: 'Royal Sapphire',
                headline: '',
                text: '',
                image: tshirt2,
                purchased: false,
                locked: true,
              },
              {
                level: 3,
                speed: 0.33,
                title: 'Radiant Ruby',
                headline: '',
                text: '',
                image: tshirt3,
                purchased: false,
                locked: true,
              },
              {
                level: 4,
                speed: 0.38,
                title: 'Honeyed Amber',
                headline: '',
                text: '',
                image: tshirt4,
                purchased: false,
                locked: true,
              },
              {
                level: 5,
                speed: 0.45,
                title: 'Epic Galaxy',
                headline: '',
                text: '',
                image: tshirt5,
                purchased: false,
                locked: true,
              },
        ],
        trousers: [
            {
                level: 1,
                speed: 0.24,
                title: 'Basic Green',
                headline: 'Green t-shirt, slow edition',
                text: 'These entry-level running shoes have minimal features and quality, providing basic comfort and support. Ideal for everyday wear, but not intended for intense sports or long-term use.',
                image: trousers1,
                purchased: false,
                locked: false,
              },
              {
                level: 2,
                speed: 0.28,
                title: 'Royal Sapphire',
                headline: '',
                text: '',
                image: trousers2,
                purchased: false,
                locked: true,
              },
              {
                level: 3,
                speed: 0.33,
                title: 'Radiant Ruby',
                headline: '',
                text: '',
                image: trousers3,
                purchased: false,
                locked: true,
              },
              {
                level: 4,
                speed: 0.38,
                title: 'Honeyed Amber',
                headline: '',
                text: '',
                image: trousers4,
                purchased: false,
                locked: true,
              },
              {
                level: 5,
                speed: 0.45,
                title: 'Epic Galaxy',
                headline: '',
                text: '',
                image: trousers5,
                purchased: false,
                locked: true,
              },
        ],
        sneakers: [
            {
                level: 1,
                speed: 0.24,
                title: 'Basic Green',
                headline: 'Green sneakers, slow edition',
                text: 'These entry-level running shoes have minimal features and quality, providing basic comfort and support. Ideal for everyday wear, but not intended for intense sports or long-term use.',
                image: sneakers1,
                purchased: false,
                locked: false,
              },
              {
                level: 2,
                speed: 0.28,
                title: 'Royal Sapphire',
                headline: '',
                text: '',
                image: sneakers2,
                purchased: false,
                locked: true,
              },
              {
                level: 3,
                speed: 0.33,
                title: 'Radiant Ruby',
                headline: '',
                text: '',
                image: sneakers3,
                purchased: false,
                locked: true,
              },
              {
                level: 4,
                speed: 0.38,
                title: 'Honeyed Amber',
                headline: '',
                text: '',
                image: sneakers4,
                purchased: false,
                locked: true,
              },
              {
                level: 5,
                speed: 0.45,
                title: 'Epic Galaxy',
                headline: '',
                text: '',
                image: sneakers5,
                purchased: false,
                locked: true,
              },
        ],
}
